apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: dev

images:
  - name: ghcr.io/cariidev/bookcars/backend
    newTag: latest
  - name: ghcr.io/cariidev/bookcars/frontend
    newTag: latest
  - name: ghcr.io/cariidev/bookcars/admin
    newTag: latest

patchesStrategicMerge:
  - backend-ingress.yaml
  - frontend-ingress.yaml
  - admin-ingress.yaml