apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: dev

images:
  - name: ghcr.io/cariidev/bookcars/backend
    newTag: latest
  - name: ghcr.io/cariidev/bookcars/frontend
    newTag: latest
  - name: ghcr.io/cariidev/bookcars/admin
    newTag: latest

patches:
  - path: backend-ingress.yaml
  - path: frontend-ingress.yaml
  - path: admin-ingress.yaml