# Add component-specific labels with selectors
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-backend
  namespace: bookcars
  labels:
    component: backend
spec:
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: bc-backend
  namespace: bookcars
  labels:
    component: backend
spec:
  selector:
    component: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bc-backend-pdb
  namespace: bookcars
  labels:
    component: backend
spec:
  selector:
    matchLabels:
      component: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-frontend
  namespace: bookcars
  labels:
    component: frontend
spec:
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: bc-frontend
  namespace: bookcars
  labels:
    component: frontend
spec:
  selector:
    component: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bc-frontend-pdb
  namespace: bookcars
  labels:
    component: frontend
spec:
  selector:
    matchLabels:
      component: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-admin
  namespace: bookcars
  labels:
    component: admin
spec:
  selector:
    matchLabels:
      component: admin
  template:
    metadata:
      labels:
        component: admin
---
apiVersion: v1
kind: Service
metadata:
  name: bc-admin
  namespace: bookcars
  labels:
    component: admin
spec:
  selector:
    component: admin
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bc-admin-pdb
  namespace: bookcars
  labels:
    component: admin
spec:
  selector:
    matchLabels:
      component: admin