apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdn-storage-pvc
  namespace: bookcars
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-logs-storage-pvc
  namespace: bookcars
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi