apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-backend
  namespace: bookcars
  labels:
    app: bc-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bc-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bc-backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - bc-backend
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: bc-backend
          image: ghcr.io/cariidev/bookcars/backend:latest
          ports:
            - containerPort: 4002
          readinessProbe:
            tcpSocket:
              port: 4002
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 4002
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: cdn-storage
              mountPath: /var/www/cdn/bookcars
            - name: api-logs-storage
              mountPath: /bookcars/api/logs
      volumes:
        - name: cdn-storage
          persistentVolumeClaim:
            claimName: cdn-storage-pvc
        - name: api-logs-storage
          persistentVolumeClaim:
            claimName: api-logs-storage-pvc