apiVersion: apps/v1
kind: Deployment
metadata:
  name: bc-admin
  namespace: bookcars
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: bc-admin
          image: ghcr.io/cariidev/bookcars/admin:latest
          ports:
            - containerPort: 3001
          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi