apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      environment: prod

# Use specific version tags for production
images:
  - name: ghcr.io/cariidev/bookcars/backend
    newTag: v1.0.0
  - name: ghcr.io/cariidev/bookcars/frontend
    newTag: v1.0.0
  - name: ghcr.io/cariidev/bookcars/admin
    newTag: v1.0.0

# Increase replicas for production
replicas:
  - name: bc-backend
    count: 5
  - name: bc-frontend
    count: 5
  - name: bc-admin
    count: 3

patches:
  - path: backend-ingress.yaml
  - path: frontend-ingress.yaml
  - path: admin-ingress.yaml
  - path: resources.yaml