name: containerize

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      environment:
        description: "dev/prod"
        required: true
        default: "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component: [frontend, backend, admin]
    env:
      REPO_PREFIX: ghcr.io/${{ github.repository }}/${{ matrix.component }}

    steps:
      - uses: actions/checkout@v4

      - name: load-env-var-${{ matrix.component }}
        uses: 1password/load-secrets-action@v2
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          ENV_DOCKER: op://carii-${{ github.event.inputs.environment || 'dev' }}/env-docker-${{ matrix.component }}/notesPlain
        with:
          export-env: true

      - name: write-env-docker-file
        run: |
          echo "$ENV_DOCKER" > ${{ matrix.component }}/.env.docker

      - name: login-ghcr
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: build-docker-image
        run: |
          REPO_PREFIX_LOWER=$(echo "$REPO_PREFIX" | tr '[:upper:]' '[:lower:]')
          docker build -t $REPO_PREFIX_LOWER:${{ github.sha }} -f ${{ matrix.component }}/Dockerfile .
          docker push $REPO_PREFIX_LOWER:${{ github.sha }}
          docker tag $REPO_PREFIX_LOWER:${{ github.sha }} $REPO_PREFIX_LOWER:latest
          docker push $REPO_PREFIX_LOWER:latest
