name: deploy
on:
  workflow_run:
    workflows: ["containerize"]
    types: [completed]
    branches: [main, dev]
  workflow_dispatch:

jobs:
  restart:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: restart-k3s-deployments
        run: |
          sudo kubectl rollout restart deployment/bc-frontend -n bookcars
          sudo kubectl rollout restart deployment/bc-backend  -n bookcars
          sudo kubectl rollout restart deployment/bc-admin -n bookcars
