name: deploy

on:
  workflow_run:
    workflows: ["containerize"]
    types: [completed]
    branches: [main, dev]
  workflow_dispatch:

jobs:
  restart:
    runs-on: self-hosted
    steps:
      - name: restart-k3s-deployments
        env:
          KUBECONFIG: /home/ansible/.kube/config
        run: |
          sudo kubectl rollout restart deployment/bc-frontend -n bookcars
          sudo kubectl rollout restart deployment/bc-backend  -n bookcars
          sudo kubectl rollout restart deployment/bc-admin -n bookcars
